function [fval,exponent,mid_price,smooth_curve,percent_error] = curve_fitting(cum_energy,sorted_prices,x0,lb,ub)
GJ_per_MWh = 3.6;
max = cum_energy(end);
GJ_prices = (sorted_prices-sorted_prices(1))*(1000/GJ_per_MWh);
fun = @(x)((max/(1+exp(-1*x(1)*(GJ_prices(1)-x(2)))))-cum_energy(1))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(2)-x(2)))))-cum_energy(2))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(3)-x(2)))))-cum_energy(3))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(4)-x(2)))))-cum_energy(4))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(5)-x(2)))))-cum_energy(5))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(6)-x(2)))))-cum_energy(6))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(7)-x(2)))))-cum_energy(7))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(8)-x(2)))))-cum_energy(8))^2+...
    ((max/(1+exp(-1*x(1)*(GJ_prices(9)-x(2)))))-cum_energy(9))^2;
options = optimoptions('fmincon','TolFun',1e-12);
[x,fval] = fmincon(fun,x0,[],[],[],[],lb,ub,[],options);
exponent = x(1);
mid_price = x(2);
smooth_curve = [max/(1+exp(-1*exponent*(GJ_prices(1)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(2)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(3)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(4)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(5)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(6)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(7)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(8)-mid_price))),...
    max/(1+exp(-1*exponent*(GJ_prices(9)-mid_price)))]';
% figure
% graph = plot(cum_energy,sorted_prices,smooth_curve,sorted_prices);
percent_error = (smooth_curve-cum_energy)./cum_energy*100;
end