# L155_elec_state_fractions.R
# Universal header file - provides logging, file support, etc.

source( "rgcam-processing-code/headers/RGCAM_header.R" )
source( "rgcam-data/Assumptions/A_RGCAM_data.R" )
logstart( "L155_elec_state_fractions.R" )
printlog( "States supply by load segments" )

# -----------------------------------------------------------------------------
# 1. Read files

states_subregions <- readdata( "states_subregions" )
USA_elec_segments <- readdata( "USA_elec_segments" )
L103_in_EJ_state_elec_F <- readdata( "L103_in_EJ_state_elec_F" )
L103_out_EJ_state_elec_F <- readdata( "L103_out_EJ_state_elec_F" )
L154_sR_elec_supply <- readdata( "L154_sR_elec_supply" )

#Initialize state electricity table
L155_out_EJ_state_elec_F <- L103_out_EJ_state_elec_F
L155_out_EJ_state_elec_F$GCAM_subregion <- states_subregions$subregion_FERC[match(L155_out_EJ_state_elec_F$state,states_subregions$state)]
L155_state_elec_supply <-merge(L155_out_EJ_state_elec_F, USA_elec_segments, by.x = "GCAM_fuel", by.y="fuel")
L155_state_elec_supply <- L155_state_elec_supply[,c("state","GCAM_subregion", "GCAM_fuel","technology","segment","X1990","X2005")]
L155_state_elec_supply <- L155_state_elec_supply[order(L155_state_elec_supply$state),]

#Add ID vector to state table
L155_state_elec_supply$ID_sR_T_Y<-paste(L155_state_elec_supply$GCAM_subregion,L155_state_elec_supply$technology,sep="")

#Merge subregion table with state table to get fractions by state
L155_state_elec_supply <-merge(L155_state_elec_supply, L154_sR_elec_supply, by.x = "ID_sR_T_Y", by.y="ID_sR_T_Y")
L155_state_elec_supply <- L155_state_elec_supply[,c("state","GCAM_subregion.x", "GCAM_fuel.x","technology.x","segment.x","X1990.x","X2005.x", "fraction1990", "fraction2005")]
L155_state_elec_supply <- L155_state_elec_supply[order(L155_state_elec_supply$state),]

#Clean up column names
names( L155_state_elec_supply )[ names( L155_state_elec_supply ) == "GCAM_subregion.x" ] <- "GCAM_subregion"
names( L155_state_elec_supply )[ names( L155_state_elec_supply ) == "GCAM_fuel.x" ] <- "GCAM_fuel"
names( L155_state_elec_supply )[ names( L155_state_elec_supply ) == "technology.x" ] <- "technology"
names( L155_state_elec_supply )[ names( L155_state_elec_supply ) == "segment.x" ] <- "segment"
names( L155_state_elec_supply )[ names( L155_state_elec_supply ) == "X1990.x" ] <- "X1990"
names( L155_state_elec_supply )[ names( L155_state_elec_supply ) == "X2005.x" ] <- "X2005"


#Calculate electricity generated by each technology in base years
L155_state_elec_supply$gen1990 <- L155_state_elec_supply$X1990*L155_state_elec_supply$fraction1990
L155_state_elec_supply$gen2005 <- L155_state_elec_supply$X2005*L155_state_elec_supply$fraction2005

#L155_state_elec_supply is only elect output. Before writing out, add elec input
L155_in_EJ_state_elec_F <- L103_in_EJ_state_elec_F
L155_in_EJ_state_elec_F$GCAM_subregion <- states_subregions$subregion_FERC[match(L155_in_EJ_state_elec_F$state,states_subregions$state)]
L155_state_elec_supply_in <-merge(L155_in_EJ_state_elec_F, USA_elec_segments, by.x = "GCAM_fuel", by.y="fuel")
L155_state_elec_supply_in <- L155_state_elec_supply_in[,c("state","GCAM_subregion", "GCAM_fuel","technology","segment","X1990","X2005","fraction1990", "fraction2005")]
L155_state_elec_supply_in <- L155_state_elec_supply_in[order(L155_state_elec_supply_in$state),]
names( L155_state_elec_supply_in )[ names( L155_state_elec_supply_in ) == "X1990" ] <- "tot_inX1990"
names( L155_state_elec_supply_in )[ names( L155_state_elec_supply_in ) == "X2005" ] <- "tot_inX2005"
L155_state_elec_supply <- cbind(L155_state_elec_supply[,1:4],L155_state_elec_supply_in[,names(L155_state_elec_supply_in) == "tot_inX1990" | 
							names(L155_state_elec_supply_in) == "tot_inX2005"],L155_state_elec_supply[,5:ncol(L155_state_elec_supply)])
L155_state_elec_supply$in1990 <- L155_state_elec_supply$tot_inX1990*L155_state_elec_supply$fraction1990
L155_state_elec_supply$in2005 <- L155_state_elec_supply$tot_inX2005*L155_state_elec_supply$fraction2005
L155_state_elec_supply <- cbind(L155_state_elec_supply[,names(L155_state_elec_supply) != "tot_inX1990" & 
							names(L155_state_elec_supply) != "tot_inX2005"])
							
#Add ID vector to Supply table
L155_state_elec_supply$ID_state_T_Y<-paste(L155_state_elec_supply$state,L155_state_elec_supply$technology,sep="")

# -----------------------------------------------------------------------------
# 3. Output
#Add comments for each table
comments.L155_state_elec_supply <- c( "Electricity supply / fuel / year","Unit = EJ" )

#write tables as CSV files
writedata( L155_state_elec_supply,fn="L155_state_elec_supply", comments=comments.L155_state_elec_supply )

# Every script should finish with this line
logstop()

