# Testing code for internal functions

context("modeltime")

library(tibble)
library(readr)

test_that("handles bad input", {
  mtdata <- modeltime()

  # For each named element in `mtdata`, load corresponding dataset
  # generated by the old data system and compare
  for(i in names(mtdata)) {
    f <- file.path("comparison_data", paste(i, "csv", sep = "."))
    expect_true(file.exists(f), label = paste0(f, "doesn't exist"))

    d <- read_csv(f, skip = 4)
    expect_equivalent(mtdata[[i]], d, label = paste(i, "doesn't match", f))
  }
})
