
on: [pull_request]

name: coverage-test

jobs:
  test-coverage:
    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies 
        run: |
          install.packages(c("renv"))
          renv::restore()
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}